name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Build and push Docker images
        uses: docker/build-push-action@v1.1.0
        with:
          username: {{ $secrets.DOCKER_USERNAME }}
          password: {{ $secrets.DOCKER_PASSWORD }}
          repository: relaysh/dynatrace-trigger-event-fired
          tags: latest
          path: triggers/dynatrace-trigger-event-fired
          add_git_labels: true
          push: true
